--==================================
--Skyler Marquis
--CIS332: Database and SQL
--Unit 2, Chapter 3 Assignment
--==================================

--Clean-up & Preparation for Running the Script--
DROP TABLE CATEGORY PURGE;
--DROP TABLE EMPLOYEES PURGE;
DROP TABLE JL_EMPS PURGE;
--DROP TABLE BOOK_PRICING PURGE;

--#1 in hands on assignments
CREATE TABLE CATEGORY
    (CatCode    VARCHAR2(2),
     CatDesc     VARCHAR2(10));
     
--VERIFICATION
DESC CATEGORY

--#2
CREATE TABLE EMPLOYEES
    (Emp#       NUMBER(5, 0),
     Lastname   VARCHAR2(10),
     Firstname  VARCHAR2(10),
     Job_class  VARCHAR2(4));
     
--VERIFICATION
DESC EMPLOYEES

--#3
ALTER TABLE EMPLOYEES ADD
    (EmpDate    DATE DEFAULT SYSDATE,
     EndDate    DATE);

--VERIFICATION
DESC EMPLOYEES

--#4
ALTER TABLE EMPLOYEES MODIFY
    (Job_class  VARCHAR2(2));
    
--VERIFICATION
DESC EMPLOYEES

--#5
ALTER TABLE EMPLOYEES DROP COLUMN EndDate;

--VERIFICATION
DESC EMPLOYEES

--#6
RENAME EMPLOYEES TO JL_EMPS;

--VERIFICATION
DESC JL_EMPS

--#7
CREATE TABLE BOOK_PRICING AS 
    (SELECT ISBN AS ID, Cost, Retail, Category FROM BOOKS);
    
--VERIFICATION
DESC BOOK_PRICING

--#8
ALTER TABLE BOOK_PRICING 
    SET UNUSED (CATEGORY);
    
--VERIFICATION
DESC BOOK_PRICING

--#9
TRUNCATE TABLE BOOK_PRICING;

--VERIFICATION
SELECT *
FROM BOOK_PRICING;

--#10
DROP TABLE BOOK_PRICING PURGE;
DROP TABLE JL_EMPS;
FLASHBACK TABLE JL_EMPS TO BEFORE DROP;

--VERIFICATION
DESC JL_EMPS